--- 
addons: 
  code_climate: 
    repo_token: 
      secure: mAuvDu+nrzB8dOaLqsublDGt423mGRyZYM3vsrXh4Tf1sT+L1PxsRzU4gLmcV27HtX2Oq9DA4vsRURfABU0fIhwYkQuZqEcA3d8TL36BZcGEshG6MQ2AmnYsmFiTcxqV5bmlElHEqQuT5SUFXLafgZPBnL0qDwujQcHukID41sE=
after_success: 
  - "bundle exec codeclimate-test-reporter"
before_install: 
  - "gem update --system"
branches: 
  only: 
    - master
    - themes
    - /*-stable/
bundler_args: "--without benchmark:site:development"
cache: bundler
env: 
  matrix: 
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
language: ruby
matrix: 
  exclude: 
    - 
      env: TEST_SUITE=cucumber
      rvm: jruby-9.1.14.0
  include: 
    - 
      env: "TEST_SUITE=test ROUGE=1.11.1"
      rvm: "2.4.2"
    - 
      env: TEST_SUITE=fmt
      rvm: "2.4.2"
    - 
      env: TEST_SUITE=default-site
      rvm: "2.4.2"
    - 
      env: ROUGE_VERSION=1.11.1
      rvm: "2.4.2"
notifications: 
  slack: 
    secure: dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4YGEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAYO1AanCUbJSEyJTju347xCBGzESU=
rvm: 
  - "2.4.2"
  - "2.3.5"
  - "2.2.8"
  - "2.1.10"
  - jruby-9.1.14.0
script: script/cibuild
sudo: false
