--- 
collections: 
  docs: 
    output: true
    permalink: "/:collection/:path/"
  posts: 
    output: true
    permalink: "/news/:year/:month/:day/:title/"
  tutorials: 
    output: true
defaults: 
  - 
    scope: 
      path: _docs
      type: docs
    values: 
      layout: docs
  - 
    scope: 
      path: _posts
      type: posts
    values: 
      image: /img/twitter-card.png
      layout: news_item
description: "Transform your plain text into static websites and blogs"
exclude: 
  - .gitignore
  - CNAME
  - icomoon-selection.json
  - readme.md
gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
logo: /img/logo-2x.png
name: "Jekyll • Simple, blog-aware, static sites"
plugins: 
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
repository: "https://github.com/aleksandrbogomolov/aleksandrbogomolov.github.io"
sass: 
  style: compressed
timezone: America/Los_Angeles
twitter: 
  username: ksandr_ua
url: "https://jekyllrb.com"
